# Generated by Django 5.1.2 on 2024-10-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='category',
            field=models.CharField(choices=[('smart', 'Smart'), ('elegant', 'Elegant'), ('classic', 'Classic'), ('sport', 'Sport')], default='smart', max_length=20, null=True),
        ),
    ]
